Fix a compilation error when using OpenSSL 1.1.0+
OpenSSL 1.1.0 introduces some API changes, causing the following
compile error:

rct/AES256CBC.cpp:24:26: error: field 'ectx' has incomplete type
'EVP_CIPHER_CTX {aka evp_cipher_ctx_st}'

This fix supports both new and old OpenSSL.